name: Hundi Fops
url: http://hundifops.github.io
destination: ./_site
twitter: hundifops
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty

exclude:
  - README.md